### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Herz3h** [arbarlow/ruby-mp4info#7]
Hello,

I would like to know if i can use this Gem in a commercial app without releasing my app source ? 

I see its licensed under GPL. Not sure if up to date.

Thanks

**Comment by arbarlow** [comment]
I believe GPL means you can modify and redistribute fine, if you modify it, then it asks you release that modification for others to use also!

**Comment by Herz3h** [comment]
Yeh i'd have to release source of my app even if i don't modify this library. The problem is that i need it for a commercial app (for my company). So i guess i can't use it then :/
